version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - maildev
      - mysql
    environment:
      MONGO_URI: mongodb://mongo:27017/testdb
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: mydb
      SMTP_HOST: maildev
      SMTP_PORT: 1025
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  maildev:
    image: maildev/maildev
    container_name: maildevs
    ports:
      - "1080:1080" # Web UI → http://localhost:1080
      - "1025:1025" # SMTP server

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminers
    restart: always
    ports:
      - 8080:8080

volumes:
  mongo-data:
  mysql-data:
